### ISSUE TITLE
Add pagination and search for leave application index view

### ISSUE THREAD

**Issue by ajinath** [joshsoftware/intranet#117]
Add pagination and search for leave application index view

**Comment by Shwetakale** [comment]
We need fix following 2 issues

+ In leave search system is showing all the employees with similar first names, even when we write full name.

![image](https://user-images.githubusercontent.com/6301532/42434711-c61f9bd6-8371-11e8-80b7-70c92568d8f7.png)

+  If we search / paginate from 'Leave History' tab then we are redirected to 'Pending leaves' tab. Search and pagination is working as expected we just need to maintain current tab selection.
