### ISSUE TITLE
Timesheet Reminder at 7:00 PM or 10:00 AM next day

### ISSUE THREAD

**Issue by anilmaurya** [joshsoftware/intranet#169]
Currently we are getting reminder at 5:00 PM , when I go fill timesheet at 5:00PM then I am getting future timestamp not allowed error because I have not finished my work till 5:00 PM.

If we are building custom notifications for users then this issue will be solved . Until then please change notification time to 7:00 PM or 10:00 Am next day.

Thanks, Anil.

**Comment by ajaysudhakaranarse** [comment]
we were testing on other day so reminder mail went out at 5PM. Now we have set this to 9.30 AM.

Thanks, Ajay.
