### ISSUE TITLE
Why restrict editing timesheet for past 2 days ?

### ISSUE THREAD

**Issue by anilmaurya** [joshsoftware/intranet#203]
<img width="1179" alt="Screen Shot 2019-04-15 at 10 25 25 AM" src="https://user-images.githubusercontent.com/1912864/56108359-25afe500-5f69-11e9-9abb-aebbb9be1e44.png">

By mistake, I have filled wrong project . Now I can't edit.

**Comment by anilmaurya** [comment]
Faced this issue again.

Please make user friendly application 🙏

**Comment by Sameer-Tilak** [comment]
Add and Edit timesheet limit should have same period.
