### ISSUE TITLE
Leads should be in the notification email list

### ISSUE THREAD

**Issue by shintre** [joshsoftware/intranet#254]
We should have names of all leads in the notification emails list. For e.g. earlier we had Shekhar, Anuja Ware but now I don't see their names. Can we add it please?

![image](https://user-images.githubusercontent.com/4318846/62754416-57efd000-ba8d-11e9-9b07-e7051ecc276a.png)

**Comment by managoliabhijit** [comment]
yes, will get this addressed Sachin.
