### ISSUE TITLE
Resource List: Few suggested features

### ISSUE THREAD

**Issue by shintre** [joshsoftware/intranet#281]
+ Filter to see all billed/ unbilled, technical skills, projects
+ Designation not showing up
+ Can we show total experience
+ Experience Prior to Josh (In Months) is this accurate?

**Comment by managoliabhijit** [comment]
@Sameer-Tilak @shintre For Total experience we can have 3 columns instead of current 2 
1st- Experience prior to Josh
2nd- Experience in Josh 
3rd- Total experience

**Comment by shintre** [comment]
We need it

**Comment by shintre** [comment]
we need total experience in Years and months
