### ISSUE TITLE
The "Leave Application" is very slow to load

### ISSUE THREAD

**Issue by shintre** [joshsoftware/intranet#287]
It feels like the link is not working.

![image](https://user-images.githubusercontent.com/4318846/65403795-335c7700-ddf3-
11e9-8873-444fab2b6a75.png)

**Comment by Sameer-Tilak** [comment]
Only load pending leaves on page load. Click on Leave history should load only first page and all other pages should be loaded in background. By default only load current calendar year leaves only. 

We already have date range, project and employee selection that can be used to get old leave details.

**Comment by managoliabhijit** [comment]
@Sameer-Tilak @shintre This is addressed, can you check once so the issue can be closed,
