### ISSUE TITLE
Collecting more details of each project assigned to developer.

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/intranet#290]
Split current project list in separate project with other details of project as follows

project | Start date | End date | Allocation % | Timesheet required Y/N

Start date is mandatory when new project is added. End date is mandatory when any project deleted.

We want to use this list for project profitability report. And also for resource allocation report.

**Comment by swapnilchincholkar** [comment]
- For project's form add new tab similar to `Tech Details` as `Team Details`. In it, have a list of members working on project. 
- While adding new member, accept above mentioned information. While adding start date, allocation are mandatory.
- While removing member from project, end date is mandatory.
- Maintain history of members worked on project i.e do not delete records rather flag them inactive.

**Comment by rohitjoshixyz** [comment]
Paraphrase: Add another tab in `projects/edit` view called team that will have a table of team members working as follows:
name | start_date | end_date | allocation% | time_sheet_required? | active?(flag)
--- | --- | --- | --- | --- | ---
Rohit | 12/03/2020 | 12/04/2021 | 70% | Yes | Yes

Could you please elaborate what we exactly mean by `Allocation %`?
I noticed the `user_project` model does not contain `allocation%` and `time_sheet_required` and `flag` fields so I should add them.

Also what if we accidentally allocated an employee to wrong project? We will also need a remove button just in case.

**Comment by swapnilchincholkar** [comment]
Code changes from @Prashantbangar03 are under https://github.com/joshsoftware/intranet/pull/332

Yes we need to accept values of `allocation` & `time_sheet_required`.
We won't be removing the allocation record, we need it hence will use an "active" flag on it.

**Comment by Sameer-Tilak** [comment]
@rohitjoshixyz @swapnilchincholkar 

Few fix required 
1. If I mark any engg as inactive on project->team detail page with correct end date, that entry should move to Ex-Employee details list. 
2. Rename "Ex-Employee Details for Star Tv" to ""Prev team members for Star Tv". This list will contain list of all members who were part of this team (irrespective whether he is current employee)
3. Can not have duplicate name in first least of current team members. But duplicate is possible in Prev team member list for different duration.
4. Project->Team detail - If error occurs on save then control should remain on same tab page. At present it goes out to main project page. 
5. Project->Update Project tab. After adding Team detail page, Team member field on this page should be non-editable.

please fix above issues / changes.

**Comment by rohitjoshixyz** [comment]
> Project->Update Project tab. After adding Team detail page, Team member field on this page should be non-editable.

This field is removed in the latest commit.

> If I mark any engg as inactive on project->team detail page with correct end date, that entry should move to Ex-Employee details list.
Rename "Ex-Employee Details for Star Tv" to ""Prev team members for Star Tv". This list will contain list of all members who were part of this team (irrespective whether he is current employee)

So we need to split team member list will into `active` and `inactive` team members. The `Ex-employee details list` contains those employees who have resigned from Josh. So you want to add those employees also in the `inactive` team member list that will be read only. _Only this list should contain duplicate names_ Correct? @Sameer-Tilak @swapnilchincholkar

**Comment by rohitjoshixyz** [comment]
@swapnilchincholkar I have pushed the necessary changes in #334 
Only pending fix is:
> Project->Team detail - If error occurs on save then control should remain on same tab page. At present it goes out to main project page.

Figuring it out
