### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/intranet#294]
Index -
1. Only show active projects in alphabetical order
2. At top add option to show all closed projects. 
3. Remove 2 columns "Allocated Employees", "No of Employees" and add single column as current team size.
4. Add hyper link on count to show Engg working on that project.

CRUD - 
1. Project start date should be mandatory
2. When project is set to active = false, project end date is mandatory.
3. When project end date is set, set same date as end date against that project entry under each Engg assigned to it.
4. Add billing freq - Monthly, Bi-weekly, adhoc
5. Project Type - T&M, Fixbid, Free, Investment , Remove is_free flag.
6. For monthly - Day of month, Bi-weekly - first invoice date, adhoc - no fix date.
7. Project Domain - Select from fixed list. One project can come under multiple domains.
8. is_activity : Add new flag. Set to 'Y' for project like "Interview" and to "N" for actual project.
9. Delete project with name - Other. It has no meaning.

**Comment by swapnilchincholkar** [comment]
Already completed.
