### ISSUE TITLE
Team api: Send designation name in api response.

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/intranet#301]
We use team-listing api on Josh website ((Request url: https://intranet.joshsoftware.com/api/v1/team))

As per updated signature, of team , UI wants designation as hash instead of string:

Ex.: `designation: {name: "Director"} `instead of `designation: "Director"`

Can anyone please fix it on priority as one of the high priority task in Josh website is dependent on this change?

cc: @Mohit-Pawar , @swapnilchincholkar , @vaibhav8186

**Comment by paritoshbotre** [comment]
Closing this issue,   @PradipDKshirsagar already resolved it.
