### ISSUE TITLE
Project Team data report

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/intranet#324]
Need report per following format

Project | Project Start Date | Project End Date | Employee Name | Employee Tech Skills | Employee Total Exp in Months | Employee Started On Project At | Days on Project

Project End date - Actual as given in project data or if empty then EOM(Today() + 6.months)
Days in project  - Today() - Employee Start date on project

first 3 columns will repeat for all engg of same project. List should be group by and order by project name.

**Comment by swapnilchincholkar** [comment]
Completed under https://github.com/joshsoftware/intranet/pull/336.

Format is:
Project | Project Start Date | Project End Date | Employee Name | Employee Tech Skills | Employee Other Skills | Employee Total Exp in Months | Employee Started On Project At | Days on Project
