### ISSUE TITLE
Timesheet Backdate Entry

### ISSUE THREAD

**Issue by Ashish944** [joshsoftware/intranet#454]
So Currently employees can fill timesheet for last 7 days. If it exceeds 7 days we need to take permission from HR and Manager. Then create a csv with timesheet details and after that HR will upload those details.

In this feature we have added a flag allow_timesheet_backdate_entry which is only accessible to HR and Admin. This flag is added under employees profile page. By default this flag will be set to false. If this flag is set to true employee will be able to fill timesheet for more than 7 days.

**Comment by abhijitkasbe** [comment]
can we have same flag to fill the time sheets more than 12 hours?
