### ISSUE TITLE
Did the newsletter in Aug go to all?

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/intranet#53]
Lightair shows: 4825 subscribed users
Sendgrid shows: 3952 requests sent.

Did we send to all? 

![screen shot 2014-09-01 at 11 18 00 am](https://cloud.githubusercontent.com/assets/61500/4104928/9493a23c-319b-11e4-966e-4358d92a27a0.png)

**Comment by Shwetakale** [comment]
Now we are only showing subscribed users count.
