### ISSUE TITLE
Not able to reject optional holiday for 14th April, applied on 12th April

### ISSUE THREAD

**Issue by anilmaurya** [joshsoftware/intranet#563]
<img width="1238" alt="Screenshot 2021-04-12 at 3 00 00 PM" src="https://user-images.githubusercontent.com/1912864/114373232-05d74a00-9ba0-11eb-9bcb-1007304a328c.png">

**Comment by tejaszambre** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Optional Holiday Validation issue](https://trello.com/c/3fj0fsXX/114-optional-holiday-validation-issue)
