### ISSUE TITLE
Add support for importing contacts (for newsletters subscriptions)

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/intranet#76]
Support a 3rd option in "Add Users" dropdown called "Import CSV". The format must be:
```
"Full Name", "Email" 
```
1. Please ensure that you check for already existing user. No duplicates should be added to the system. 
2. All these new users should be subscribed automatically for newsletter (i.e. is_subscribed: true) 
3. Set the source_data: "Business Card"

**Comment by gautamrege** [comment]
what's the ETA on this.. I have a list ready for upload.

**Comment by anujaware** [comment]
Not yet done. Will do this today and will let you know.

**Comment by anujaware** [comment]
Done and deployed on production. After successful processing you will get an email with attachment of failed users with reason.
Please check and let me know if there is any issue.
