### ISSUE TITLE
Project Edit overriding details of another tab

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/intranet#79]
If we update tech details tab, Project details (members) gets deleted.

**Comment by anujaware** [comment]
This is happening because we are not using nested form for user under project form. We need to check why we are not using nested form and use it if possible.
For now fixed this by adding flag on Tech details form. (Please refer code from above commit.)

**Comment by Sameer-Tilak** [comment]
Very old issue. And may have been fixed. Closing for now.
