### ISSUE TITLE
cant login with josh account

### ISSUE THREAD

**Issue by rageshpillai** [joshsoftware/intranet#83]
google authentication failed (400) error when clicking "sign in with josh account"

**Comment by shintre** [comment]
It will fail as you don't have a Josh account. Are you pointing at some underlying issue?

**Comment by rageshpillai** [comment]
how to configure it ?

**Comment by sethu** [comment]
You have configure your own google authentication for you organization or individual and set the configuration. Currently, it expects the josh software account to login, we will remove the default to mandate the user to configure it before using it.

https://developers.google.com/identity/protocols/OAuth2

**Comment by Shwetakale** [comment]
This has been fixed.
