### ISSUE TITLE
Blog feed not working for blogger

### ISSUE THREAD

**Issue by anilmaurya** [joshsoftware/intranet#85]
![screen shot 2016-01-05 at 11 43 00 am](https://cloud.githubusercontent.com/assets/1912864/12108931/bbb5ee4e-b3a2-11e5-9954-0bcc5d0b40e8.png)

**Comment by Shwetakale** [comment]
@anilmaurya This is because we are parsing feeds and feed URL for ```wordpress``` and ```blogpost``` are different. For ex. JoshSoftware blogs on wordpress Its feed url is ```http://blog.joshsoftware.com/feed/``` and you blogs on blogpost whose feed url is ```http://programmingright.blogspot.in/feeds/posts/default``` . Currently only feeds parsing of ```wordpress``` is handled.

**Comment by Shwetakale** [comment]
@anilmaurya @sethu There could be different feed url's and user can also configure feed url so I think way to fix this is instead of using blog url for fetching feeds we can add one more field blog feed url and fetch feeds from that url. Thoughts?

**Comment by anilmaurya** [comment]
Please do the needful 👍

**Comment by Sameer-Tilak** [comment]
Too old issue. May have been fixed. Closing for now.
