### ISSUE TITLE
Broken Github links on Employee details page.

### ISSUE THREAD

**Issue by prasadsurase** [joshsoftware/intranet#93]
The github links on the employee details page in the 'Github' tab are broken. The link domain should be github.com and not intranet.joshsoftware.com.

<img width="1226" alt="screen shot 2016-09-23 at 12 53 50 pm" src="https://cloud.githubusercontent.com/assets/562052/18777450/d7de3258-818c-11e6-8082-3baf977d3420.png">

**Comment by Shwetakale** [comment]
This is deployed.
