### ISSUE TITLE
Check why redactor code button is not showing up

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/intranet#96]
We use redactor as an editor for creating newsletter and policies. But, now code button in those editor is not showing up and this happened when we set up new server essentially gem has fetched again. Check what broke this functionality or replace this editor with ckeditor or tinymce.

**Comment by Sameer-Tilak** [comment]
Too old issue. May have been fixed. Closing for now.
I think newsletter is not created from this now.
