### ISSUE TITLE
Bugs on leave edit page

### ISSUE THREAD

**Issue by Shwetakale** [joshsoftware/intranet#98]
@SagareGanesh reported some issues on Leave application edit page
- [x] Datepicker is not working
- [ ] Inconsistency in date format
- [ ] Some wrong message from server when he enters date manually. I don't remember exact error message but need to check this out.

**Comment by prasadsurase** [comment]
@Shwetakale IMO the date fields should not be manually editable. The datepicker fails to work when server side validation errors are present during adding/editing a leave application. The error is from the 'bootstrap-datepicker-rails' gem's js file.

**Comment by Shwetakale** [comment]
@prasadsurase Could you please try by downgrading version of ```bootstrap-datepicker-rails ``` because it used to work earlier and if you look at [this](https://github.com/joshsoftware/intranet/commit/6ed32fe05a08224d2dfd1853c7b31e20efd29431) here version is upgraded. Also I guess downgrading version of ```redactor-rails``` may solve [this](https://github.com/joshsoftware/intranet/issues/96).

**Comment by Shwetakale** [comment]
@prasadsurase I have downgraded versions and deployed now 1st issue is resolved.

**Comment by prasadsurase** [comment]
@SagareGanesh Could you please add more details about the date format inconsistencies?

**Comment by Sameer-Tilak** [comment]
Too old issue. May have been fixed. Closing for now.
